version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/jyang-nimbusblog.com
    environment:
      HUGO_BUILD_DIR: ~/jyang-nimbusblog.com/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run:
          name: Install AWS CLI
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $HUGO_BUILD_DIR \
              s3://jyang-nimbusblog.com --delete
            else
              echo "Not master branch, dry run only"
            fi