version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo
      S3_BLOG_BUCKET: s3://jyang-nimbusblog.com
      CLOUDFRONT_ID: E32CT10S37XQPL
    steps:
      - run: apk update && apk add git
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
      - run:
          name: Build with Hugo
          command: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR --theme dimension
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $HUGO_BUILD_DIR \
              $S3_BLOG_BUCKET --delete
            else
              echo "Not master branch, dry run only"
            fi
      - run:
          name: Invalidate cloudfront cache to ensure delivery of new files
          command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --path "/*"
